training:
  # This prefix is applied to the filename when saving the model; if not specified a date/time is used
  prefix: example

  # Number of training epochs
  N_epochs: 10

  # Optimizer learning rate
  lr: 0.001

  # Batch size used over both training and testing datasets   
  batch_size: 3

  # Limit the maximum number of samples to this number 
  # If unspecified then all samples available for the specified vowel classes and gender are used
  max_samples: 24

  # This number should be an integer and it is used to deterine the split between the training and testing datasets
  # (1/train_test_divide) * (the total number of samples) is the size of the test dataset
  # e.g. for a value of 3, 2/3 of the total number of samples are used for training and 1/3 are used for testing
  train_test_divide: 3

  # If true, k-fold cross validation is performed where k is the value specified above for train_test_divide
  use_cross_validation: false

data:
  # Sampling rate to use for vowel data
  sr: 10000    

  # Which gender to pull vowel data from. Can be one of women, men, or both. 
  # If both, training and testing datasets distributed equally over the genders
  gender: both

  # Which vowel classes to train on.
  # Can be any elements from the set: [ae, eh, ih, oo, ah, ei, iy, uh, aw, er, oa, uw].
  vowels: 
    - ei
    - iy
    - oa

geom:
  # Use the (currently hardcoded) design region which sits between the src and probes with a 5 gride cell buffer
  use_design_region: true

  # Use a random initialization for the distribution of c
  use_rand_init: false

  # Number of grid cells in x-dimension of simulation domain
  Nx: 140

  # Number of grid cells in y-dimension of simulation domain
  Ny: 140

  # Time step (spatial step size is determined automatically)
  dt: 0.707

  # Wave speed background value (e.g. in PML and non-design region)
  c0: 1.0

  # Wave speed value to use with c0 during binarization
  c1: 0.9

  # Probe x-coordinates in grid cells
  px: 

  # Probe y-coordinates in grid cells
  py: 

  # Spacing, in number grid cells, between probe points
  pd: 30

  # Source x-coordinate in grid cells
  src_x: 

  # Source y-coordinate in grid cells
  src_y:

  pml:
    N: 20    # PML thickness in number of grid cells
    p: 4.0   # PML polynomial order
    max: 3.0 # PML max dampening factor

  nonlinearity:
    b0: 0.0   # Saturable abs. strength
    uth: 1.0  # Saturable abs. threshold

  binarization:
    beta: 100   # These parameterize the binarization projection function
    eta: 0.5    # see the Angler supplementary info for now
