training:
  prefix: vow3_NL
  N_epochs: 20
  lr: 0.0004
  batch_size: 9
  max_samples: 162
  train_test_divide: 3
  use_cross_validation: false
data:
  sr: 10000
  gender: both
  vowels: 
    - ae
    - ei
    - iy
geom:
  use_design_region: true
  use_rand_init: false
  Nx: 120
  Ny: 150
  dt: 0.707
  c0: 1.00
  c1: 0.80
  px: 
  py: 
  pd: 35
  src_x: 
  src_y:
  pml:
    N: 20
    p: 4.0
    max: 3.0
  nonlinearity:
    b0: 0.05
    uth: 0.25
  binarization:
    beta: 100
    eta: 0.5
