seed:
dtype: float32
training:
  prefix: satdamp
  N_epochs: 30
  lr: 0.0004
  batch_size: 9
  max_samples: 
  N_folds: 5
  cross_validation: true
data:
  window_size: 1000
  sr: 10000
  gender: both
  vowels: 
    - ae
    - ei
    - iy
geom:
  use_design_region: true
  init: half
  Nx: 160
  Ny: 100
  dt: 1.0
  h:  1.4283556979968262
  c0: 1.00
  c1: 0.5
  px: 
  py: 
  pd: 20
  src_x: 
  src_y:
  pml:
    N: 20
    p: 4.0
    max: 3.0
  nonlinearity:
    cnl: 0.0
    b0: 0.2
    uth: 9e-5
  binarization:
    beta: 100
    eta: 0.5
